### ISSUE TITLE
zoom in (magnify) Java window?

### ISSUE THREAD

**Issue by buckyster** [jdmonin/JSettlers2#14]
Love the game, but I have to squint to see the text and graphics. Is there an easy way to zoom in the entire Java window? Similar to how in a web browser I can set zoom to 150%.

**Comment by jdmonin** [comment]
Hi, if you're still out there this has finally been fixed: issue #58 provides automatic high-DPI support.

It's built into the latest "beta" JAR available at http://nand.net/jsettlers/beta2/JSettlers2.jar

**Comment by jdmonin** [comment]
Newly released v2.0.00 includes this fix. Thank you :)
