### ISSUE TITLE
Problem with UI colors depending on system theme

### ISSUE THREAD

**Issue by Fyren** [jdmonin/JSettlers2#15]
My system color theme is white text on black backgrounds.  On the first few panels shown when I run JSettlers.jar, all of the buttons and fields are black text on black backgrounds.  I see a few places in the source where the foreground color is explicitly set to black, but the background doesn't seem to be set besides for the green panel backgrounds.  I assume the button and field background colors are defaulting to my system theme.

If I comment out, for example, the setForeground(Color.black) calls in both SOCPlayerClient and SOCConnectOrPracticePanel, then those initial buttons/fields end up with white text on black backgrounds, but of course not ones in later windows (like the actual game).

I'm using Windows, if it's relevant.

**Comment by jdmonin** [comment]
Update: The long-term fix for this will probably rewrite the client UI to use Swing APIs for better accessibility, instead of older AWT classes.

**Comment by jdmonin** [comment]
Hi, if you're still following this issue, thanks for your patience :)  The latest build uses Swing and tries to detect windows theme dark/light colors.  If you'd like, please download that build from http://nand.net/jsettlers/beta2/  and let me know if it's better now.

**Comment by Fyren** [comment]
I started up a game and played a few minutes against the AI.  I think everything was readable for me.

**Comment by jdmonin** [comment]
Thanks, that's great news. Thank you very much for taking time to test this fix to such an old issue and getting back to me!

**Comment by jdmonin** [comment]
Newly released v2.0.00 includes this fix. Thank you :)
