### ISSUE TITLE
AIs abandon game after 4 hours

### ISSUE THREAD

**Issue by solmssen** [jdmonin/JSettlers2#19]
Hi - I often start a JSettlers game before I go to sleep, and play a little while until I fall asleep. It would be nice to finish those games in the morning, but the AIs abandon the game after 4 hours. Is this a timeout value I can change in the code? or something that could be exposed in the next release in the UI somewhere? Many thanks for all the work - I do love the game. Best, Andrew...

**Comment by jdmonin** [comment]
Hi, I will take a look. On a shared server the bots will wander away from inactive games, but if you're using Practice mode it would be polite of them to wait around. :)

**Comment by solmssen** [comment]
thanks! that's great! very much appreciated...

**Comment by jdmonin** [comment]
Hi Andrew,

Thanks again for suggesting this!  I've added this enhancement in commit b5370f1.

Version 1.1.20 is almost ready to release. You can download a v1.1.20 JAR which includes this enhancement from http://nand.net/jsettlers/JSettlers.jar , or a development v2.0.00 JAR from http://nand.net/jsettlers/beta2/JSettlers.jar .  Let me know if this takes care of the bots overnight for you :)

I'm glad you enjoy JSettlers. It's been a lot of fun for me too!

Thanks again,
-Jeremy

**Comment by solmssen** [comment]
thanks so much Jeremy! will check it out and report back...

**Comment by solmssen** [comment]
Jeremy, I'm happy to report that the AIs are staying in practice games that are idle more than 4 hours now. On a different note, I used it on my Lenovo Yoga 2 Pro for the first time, which has a 3200x1800 high-dpi screen, and the app came up very tiny (it is not DPI-aware?). Is there a way to fix this other than changing screen resolution to 1600x900 before playing? Should I open a new issue?

**Comment by jdmonin** [comment]
OK, good to hear!

Java can be tricky about being DPI-aware, especially across Java versions. It won't be a quick fix, unfortunately.

The closest issue open now for that here is https://github.com/jdmonin/JSettlers2/issues/14 . If you want you can comment on that, or open a new one if you feel #14 is too different from what you have in mind.

Thank you again!

**Comment by jdmonin** [comment]
JSettlers 1.1.20 containing this fix is now released and available for download.

**Comment by jdmonin** [comment]
Hi, if you're still following this issue, the fix in issue #58 provides automatic high-DPI support.

It's built into the latest "beta" JAR available at http://nand.net/jsettlers/beta2/JSettlers2.jar

**Comment by solmssen** [comment]
thanks Jeremy! this is great!
