### ISSUE TITLE
javadoc are not generated

### ISSUE THREAD

**Issue by alesky78** [jdmonin/JSettlers2#22]
[javadoc-build-patch.txt](https://github.com/jdmonin/JSettlers2/files/575380/javadoc-build-patch.txt)

running the javadoc build targets the documentation is not generated

proposed fix:
change in  build.xml the  target name="javadoc"
source="1.4" to source="1.5"

here the output of theant task execution

Buildfile: C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\build.xml
Trying to override old definition of task javac
Trying to override old definition of task javadoc
init:
init-libs:
javadoc:
    [mkdir] Created dir: C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\target\docs\api
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] Loading source files for package net.nand.util.i18n...
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\ParsedPropsFilePair.java:80: error: generics are not supported in -source 1.4
  [javadoc]     private List<FileKeyEntry> parsed;
  [javadoc]                 ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\ParsedPropsFilePair.java:168: error: enhanced for loops are not supported in -source 1.4
  [javadoc]         for (final FileEntry kp: cont)
  [javadoc]                                ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] Loading source files for package net.nand.util.i18n.gui...
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFileParser.java:77: error: generics are not supported in -source 1.4
  [javadoc]     public static List<KeyPairLine> parseOneFile(final File pFile)
  [javadoc]                       ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFileParser.java:243: error: enhanced for loops are not supported in -source 1.4
  [javadoc]         for (KeyPairLine kp : kpLines)
  [javadoc]                             ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFilePseudoLocalizer.java:77: error: generics are not supported in -source 1.4
  [javadoc]         List<PropsFileParser.KeyPairLine> pairs = PropsFileParser.parseOneFile(srcPropFile);
  [javadoc]             ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFilePseudoLocalizer.java:79: error: enhanced for loops are not supported in -source 1.4
  [javadoc]         for (PropsFileParser.KeyPairLine pair : pairs)
  [javadoc]                                               ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFileWriter.java:201: error: generics are not supported in -source 1.4
  [javadoc]         (PrintWriter pw, final String key, final String val, final List<String> comments, final boolean spacedEquals)
  [javadoc]                                                                        ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\PropsFileWriter.java:204: error: enhanced for loops are not supported in -source 1.4
  [javadoc]             for (String c : comments)
  [javadoc]                           ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:121: error: generics are not supported in -source 1.4
  [javadoc]     private List<String> newDestComments;
  [javadoc]                 ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:229: error: annotations are not supported in -source 1.4
  [javadoc]     @SuppressWarnings("serial")
  [javadoc]      ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:470: error: enhanced for loops are not supported in -source 1.4
  [javadoc]                 for (Map.Entry<String, String> kv : dk.entrySet())
  [javadoc]                                                   ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1714: warning: as of release 5, 'enum' is a keyword, and may not be used as an identifier
  [javadoc]     public static enum CellStatus
  [javadoc]                   ^
  [javadoc]   (use -source 5 or higher to use 'enum' as a keyword)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1714: error: ';' expected
  [javadoc]     public static enum CellStatus
  [javadoc]                                  ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1717: error: not a statement
  [javadoc]         DEFAULT,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1717: error: ';' expected
  [javadoc]         DEFAULT,
  [javadoc]                ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1719: error: not a statement
  [javadoc]         COMMENT_KEY_COL,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1719: error: ';' expected
  [javadoc]         COMMENT_KEY_COL,
  [javadoc]                        ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1724: error: not a statement
  [javadoc]         SEARCH_MATCH,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1724: error: ';' expected
  [javadoc]         SEARCH_MATCH,
  [javadoc]                     ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1726: error: not a statement
  [javadoc]         SRC_EMPTY_ERROR,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1726: error: ';' expected
  [javadoc]         SRC_EMPTY_ERROR,
  [javadoc]                        ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1728: error: not a statement
  [javadoc]         DEST_EMPTY,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1728: error: ';' expected
  [javadoc]         DEST_EMPTY,
  [javadoc]                   ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1730: error: not a statement
  [javadoc]         DEST_ONLY_ERROR,
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1730: error: ';' expected
  [javadoc]         DEST_ONLY_ERROR,
  [javadoc]                        ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1732: error: not a statement
  [javadoc]         READONLY_NOT_LOCALIZED
  [javadoc]         ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PropertiesTranslatorEditor.java:1732: error: ';' expected
  [javadoc]         READONLY_NOT_LOCALIZED
  [javadoc]                               ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PTEMain.java:81: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PTEMain.java:95: error: generics are not supported in -source 1.4
  [javadoc]     private final ArrayList<PropertiesTranslatorEditor> ptes;
  [javadoc]                            ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] Loading source files for package net.nand.util.i18n.mgr...
  [javadoc] Loading source files for package org.fedorahosted.tennera.antgettext...
  [javadoc] Loading source files for package soc.baseclient...
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\gui\PTEMain.java:546: error: enhanced for loops are not supported in -source 1.4
  [javadoc]         for (final PropertiesTranslatorEditor pte : ptes)
  [javadoc]                                                   ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\net\nand\util\i18n\mgr\StringManager.java:92: error: variable-arity methods are not supported in -source 1.4
  [javadoc]     public final String get(final String key, final Object ... arguments)
  [javadoc]                                                            ^
  [javadoc]   (use -source 5 or higher to enable variable-arity methods)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\baseclient\SOCDisplaylessPlayerClient.java:142: error: generics are not supported in -source 1.4
  [javadoc]     protected Hashtable<String,?> channels = new Hashtable<String,Object>();
  [javadoc]                        ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] Loading source files for package soc.client...
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\AskDialog.java:75: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\AWTClickTester.java:37: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\AWTToolTip.java:41: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ChannelFrame.java:53: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ChannelFrame.java:64: error: generics are not supported in -source 1.4
  [javadoc]     Vector<String> history = new Vector<String>();
  [javadoc]           ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ColorSquare.java:45: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ColorSquareLarger.java:38: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\FaceChooserFrame.java:59: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\NewGameOptionsFrame.java:91: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\NewGameOptionsFrame.java:125: error: generics are not supported in -source 1.4
  [javadoc]     private Map<String, SOCGameOption> opts;
  [javadoc]                ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\NewGameOptionsFrame.java:416: error: enhanced for loops are not supported in -source 1.4
  [javadoc]             for (SOCGameOption opt : opts.values())
  [javadoc]                                    ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\NotifyDialog.java:40: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:85: error: generics are not supported in -source 1.4
  [javadoc]     void diceRolledResources(List<Integer> pnum, List<SOCResourceSet> rsrc);
  [javadoc]                                  ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:442: warning: as of release 5, 'enum' is a keyword, and may not be used as an identifier
  [javadoc]     enum UpdateType
  [javadoc]     ^
  [javadoc]   (use -source 5 or higher to use 'enum' as a keyword)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:443: error: = expected
  [javadoc]     {
  [javadoc]     ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:444: error: <identifier> expected
  [javadoc]         Clay,
  [javadoc]             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:444: error: ';' expected
  [javadoc]         Clay,
  [javadoc]              ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:445: error: illegal start of type
  [javadoc]         Ore,
  [javadoc]            ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:446: error: = expected
  [javadoc]         Sheep,
  [javadoc]              ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:447: error: = expected
  [javadoc]         Wheat,
  [javadoc]              ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:448: error: = expected
  [javadoc]         Wood,
  [javadoc]             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:450: error: = expected
  [javadoc]         Unknown,
  [javadoc]                ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:452: error: = expected
  [javadoc]         Resources,
  [javadoc]                  ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:454: error: = expected
  [javadoc]         ResourceTotalAndDetails,
  [javadoc]                                ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:456: error: = expected
  [javadoc]         Road,
  [javadoc]             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:457: error: = expected
  [javadoc]         Settlement,
  [javadoc]                   ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:458: error: = expected
  [javadoc]         City,
  [javadoc]             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:459: error: = expected
  [javadoc]         Ship,
  [javadoc]             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:460: error: = expected
  [javadoc]         Knight,
  [javadoc]               ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:467: error: = expected
  [javadoc]         GoldGains,
  [javadoc]                  ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:470: error: = expected
  [javadoc]         Warship,
  [javadoc]                ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:473: error: = expected
  [javadoc]         Cloth,
  [javadoc]              ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:476: error: = expected
  [javadoc]         WonderLevel,
  [javadoc]                    ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:478: error: = expected
  [javadoc]         VictoryPoints,
  [javadoc]                      ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:479: error: = expected
  [javadoc]         SpecialVictoryPoints,
  [javadoc]                             ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:480: error: = expected
  [javadoc]         DevCards,
  [javadoc]                 ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:481: error: = expected
  [javadoc]         LongestRoad,
  [javadoc]                    ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\PlayerClientListener.java:483: error: = expected
  [javadoc]     }
  [javadoc]     ^
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ServerGametypeInfo.java:115: error: generics are not supported in -source 1.4
  [javadoc]     public Map<String,SOCGameOption> optionSet = null;
  [javadoc]               ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ServerGametypeInfo.java:207: error: enhanced for loops are not supported in -source 1.4
  [javadoc]             for (String oKey : servOpts.keySet())
  [javadoc]                              ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\ShadowedBox.java:34: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SnippingTextArea.java:37: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCAccountClient.java:75: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCApplet.java:73: error: annotations are not supported in -source 1.4
  [javadoc]     @Override
  [javadoc]      ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCBoardPanel.java:125: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCBoardPanel.java:894: error: generics are not supported in -source 1.4
  [javadoc]     private Set<Integer> portHexCoords;
  [javadoc]                ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCBoardPanel.java:3444: error: enhanced for loops are not supported in -source 1.4
  [javadoc]         for (Integer edge : lse)
  [javadoc]                           ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCBuildingPanel.java:51: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCChoosePlayerDialog.java:51: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCConnectOrPracticePanel.java:54: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCDiscardOrGainResDialog.java:53: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCFaceButton.java:54: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCFaceButton.java:151: error: generics are not supported in -source 1.4
  [javadoc]             Class<?> clazz = c.getClass();
  [javadoc]                  ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCHandPanel.java:82: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCHandPanel.java:331: error: generics are not supported in -source 1.4
  [javadoc]     private ArrayList<SOCInventoryItem> inventoryItems;
  [javadoc]                      ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCHandPanel.java:1181: error: enhanced for loops are not supported in -source 1.4
  [javadoc]             for (SOCPlayer.SpecialVPInfo svpi : svpis)
  [javadoc]                                               ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCMonopolyDialog.java:32: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerClient.java:132: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerClient.java:267: error: generics are not supported in -source 1.4
  [javadoc]     protected Hashtable<String, SOCGame> games = new Hashtable<String, SOCGame>();
  [javadoc]                        ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerClient.java:1910: error: enhanced for loops are not supported in -source 1.4
  [javadoc]                         for (SOCScenario sc : changeScens)
  [javadoc]                                             ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerInterface.java:105: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerInterface.java:1531: error: variable-arity methods are not supported in -source 1.4
  [javadoc]     public void printKeyed(final String key, final Object ... params)
  [javadoc]                                                           ^
  [javadoc]   (use -source 5 or higher to enable variable-arity methods)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerInterface.java:1599: error: generics are not supported in -source 1.4
  [javadoc]     public void began(Vector<String> members)
  [javadoc]                             ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPlayerInterface.java:3249: error: enhanced for loops are not supported in -source 1.4
  [javadoc]             for (PlayerClientListener.UpdateType t : types)
  [javadoc]                                                    ^
  [javadoc]   (use -source 5 or higher to enable for-each loops)
  [javadoc] Loading source files for package soc.client.stats...
  [javadoc] Loading source files for package soc.debug...
  [javadoc] Loading source files for package soc.disableDebug...
  [javadoc] Loading source files for package soc.game...
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCPracticeAskDialog.java:31: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCQuitAllConfirmDialog.java:34: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCQuitConfirmDialog.java:32: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCSpecialItemDialog.java:77: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SOCSpecialItemDialog.java:382: error: generics are not supported in -source 1.4
  [javadoc]     private JComponent buildRequirementsText(final List<SOCSpecialItem.Requirement> reqs)
  [javadoc]                                                        ^
  [javadoc]   (use -source 5 or higher to enable generics)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\client\SpeechBalloon.java:46: error: annotations are not supported in -source 1.4
  [javadoc] @SuppressWarnings("serial")
  [javadoc]  ^
  [javadoc]   (use -source 5 or higher to enable annotations)
  [javadoc] C:\Users\Public\work\GIT-REPOSITORY\JSettlers2\src\java\soc\game\SOCGame.java:8356: warning: as of release 5, 'enum' is a keyword, and may not be used as an identifier
  [javadoc]     public static enum SeatLockState
  [javadoc]                   ^
  [javadoc]   (use -source 5 or higher to use 'enum' as a keyword)
  [javadoc] Loading source files for package soc.message...
  [javadoc] Loading source files for package soc.robot...
  [javadoc] Loading source files for package soc.server...
  [javadoc] Loading source files for package soc.server.database...
  [javadoc] Loading source files for package soc.server.genericServer...
  [javadoc] Loading source files for package soc.util...
  [javadoc] 100 errors
  [javadoc] 3 warnings
BUILD SUCCESSFUL
Total time: 11 seconds

**Comment by jdmonin** [comment]
Thank you Alessandro, I'll look into this soon.

**Comment by jdmonin** [comment]
I wanted to also update some other javadoc options; see new commit acc5cce. Thanks again for seeing the issue and suggesting this fix.

**Comment by jdmonin** [comment]
When you're generating patches or diffs, please watch for extraneous whitespace changes which can distract from the real change being shown in the patch. :)

**Comment by jdmonin** [comment]
If this is still giving you any trouble, please let me know and I'll reopen it.
