### ISSUE TITLE
remembering last game settings

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#28]
is there a way to make last game settings remembered? for example i often set vp to 15 and set specific number of players. is it possible for java to remember that?

**Comment by jdmonin** [comment]
Thank you for the suggestion! Right now the server can have default game options through its properties file, but the client doesn't have a user-friendly way to do so.

**Comment by kotc** [comment]
it could be done as 'save/load settings (or game template)'

**Comment by jdmonin** [comment]
Formally added to roadmap/todo list. Thanks again!
