### ISSUE TITLE
problems starting game on x86 linux laptop

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#30]
when i click on the 'practice' then 'create a game' i get following yellow error box:
"Problem starting practice server: java.lang.IllegalStateException". on console i get:
"No user database available: JDBC driver is unavailable: com.mysql.jdbc.Driver: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
Users will not be authenticated."
similarly, when i try to create a server: "Problem starting server: java.lang.IllegalStateException"
and it hangs. trying to start it again results in: "java.net.BindException: Address already in use"
but connecting to it just hangs.

Java Settlers Server 2.0.00, build JM20170629
java version "1.8.0_131"
os: x86 slackware

same jar works on windows box. could it be a reason of java env? tried also java6, same results

**Comment by jdmonin** [comment]
Hi again,

Thanks for taking the time to check on different environments, that definitely helps narrow things down!

I think I've recently solved this issue with 456c4cd.   The latest build is JM20170717, please download that build from http://nand.net/jsettlers/beta2/  (or pull master and build your own) and let me know if it's working for you again. I tested it on CentOS 6.9 and MacOS 10.9.

Thanks,
-Jeremy

**Comment by kotc** [comment]
yup, tested and it works. thanks for uploading new version :)

**Comment by jdmonin** [comment]
Glad to hear!
