### ISSUE TITLE
Shorthand resource name ambiguity

### ISSUE THREAD

**Issue by generateui** [jdmonin/JSettlers2#44]
Currently, JSettlers uses the names in resources WOOD and WHEAT. while these names definitely make sense, when you shorten them to one letter, they are ambiguous ("W"). 

I would like to propose a change for either name. The easiest change for me seems to rename WOOD to TIMBER. This will result in the following names with one-letter-ascii-shorthands:

T Timber
W WHeat
S Sheep
C Clay
O Ore
U Unknown
G Gold

This change is a preparation to later enable shorthand ascii characters to refer to resources. E.g. "Player 1 discards [ww tt o c]".

**Comment by jdmonin** [comment]
For what it's worth here are the currently-official english terms from the 5th-edition rules:

- resources: brick, lumber, grain, ore, wool (no ambiguous "W")
- tile types: hills, forest, fields, mountains, pasture, desert
- dev cards: knight, progress (road building, year of plenty, monopoly), VP (market, library, chapel, university, great hall)

jsettlers code and UI currently uses some previous-edition names that could probably be updated.

**Comment by jdmonin** [comment]
Thanks again for discussing this, back in the day :) Added to Todo list for eventual name standardization.
