### ISSUE TITLE
Board incomplete on restart

### ISSUE THREAD

**Issue by PCBDMF** [jdmonin/JSettlers2#45]
Frequently when restarting a game only the top left corner of the board is visible.  The rest of the board is purple.  Game is normal within that corner (initial settlements and roads can be placed) but nowhere else.
![settlers](https://user-images.githubusercontent.com/42427106/44185093-4bd26c00-a0e0-11e8-8609-f249ce60ff68.jpg)

**Comment by jdmonin** [comment]
Thanks, still looking into this. Workaround is to resize the window by a significant amount, so it will rescale the board and its panel. Please let us know if that workaround doesn't work.

**Comment by jdmonin** [comment]
Game window / board panel layout has been reworked as part of v2.0.00. If this bug comes up again, please reopen. Thank you :)
