### ISSUE TITLE
[modding] new maps with rulesets

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#46]
would be great if particular map be stored/loaded as a text config for example as a set of rules + letters map.
[config]
name=some name
rule1=val1
rule2=val2
[map]
sslllss
sllwLs

for map tiles:
s - sea
S - sea or random land (without gold)
l - random land (without gold)
L - random land (with gold)
w/e/c/o/h/g - wood, wheat, clay, ore, sheep, gold
upper case of above - random land or gold
---
additional features:
- network db of maps (with ratings)
- network db of themes (tiles/window backgrounds)
---
that way users could provide more maps without being stuck to few predefined ones (but i'm very grateful for current selection too!). there is new map based on on the outline of europe which gave me the idea

**Comment by jdmonin** [comment]
Thanks again, I'm adding this to the roadmap/todo list in Readme.developer.md.

Meanwhile, for saving and loading a game, v2.3 added a json savegame format and `*SAVEGAME*`, `*LOADGAME*` debug commands. It's a complex format with extra server setup needed, but it may be useful depending on goals. Details in Readme.developer.md.
