### ISSUE TITLE
long timeouts when bot cant move

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#47]
problem: bot cant move -> giving up eventually, but happens again next turn.
possible solution: shorten safety timeouts needed? 3-4s max for ai? or remembering the inability to move and just skipping the bot for the rest of the game?

**Comment by jdmonin** [comment]
Good point. I think it makes sense to remember recent inability to move, and shorten that particular bot's timeout after it gives up a couple of times.  Could add a new field to SOCPlayer and check or increment it in SOCServer.checkForExpiredTurns, for example.
