### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by Saadmaghani** [jdmonin/JSettlers2#48]
The D.ebugPrintln is empty. Is debugging working?

**Comment by jdmonin** [comment]
Hello,

D.ebugPrintln is turned on or off for each java class by the import at the top of the file.

For example if you wanted to see D.ebugPrintln output for `soc.game.SOCPlayer`,  in SOCPlayer.java you would change the line

    import soc.disableDebug.D;

to

    import soc.debug.D;

Hope this helps :)
