### ISSUE TITLE
[question/bug] winning while other player has winning points

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#56]
situation:
- build from 20190220
- playing to 15pt
- 6pl map
- other player gets to 17pt out of their turn
- in my turn i get to 15pt and i'm the winner
is this according to some ruleset or a bug?

**Comment by jdmonin** [comment]
Hi, nice question!

That sounds like a very intense game :)  How many actual players were there, were all 6 seats occupied? Did they get to 17 with Special Building, or break someone else's longest road?

Anyway, that outcome is according to the rules PDF. The first person to get the winning VP total during their turn is the winner, even if another player has more points. So ```SOCGame.checkForWinner() ``` checks only the current player's total, not other players.

There's a bit of discussion and a few links at https://boardgames.stackexchange.com/questions/27199/is-it-possible-to-lose-catan-to-a-player-with-fewer-points-than-you .

Thanks,
-Jeremy

**Comment by kotc** [comment]
thanks for the confirmation! as for the game details, 2 human players, 2 bots and 2 seats free (we like to play 4pl games on 6pl maps because they take longer and allow nice building satisfaction), other human player built settlement on the island (getting 1+2VP), which totals to 17VP.

**Comment by jdmonin** [comment]
Nice, that's a good time :)  My friends and I also use the 6-player board for the same reasons.
