### ISSUE TITLE
long timeouts when bot1 hangs, yet, other bot2 tries to trade to bot1

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#57]
situation:
- bot1 appears to hang in it's decision making algo
- bot2 offers a trade ONLY to bot1
- game hangs for quite long because it happens in few consecutive bot2 rounds

expectation: detection of hung bots and/or applying 'auto trade timeout' to bots too

**Comment by jdmonin** [comment]
Thanks for this suggestion.

It looks like this might be doable in ```SOCGameHandler.endTurnIfInactive()``` by checking if trade is offered to any humans, or only bots, and for bots using a shorter timeout than ```ROBOT_FORCE_ENDTURN_TRADEOFFER_SECONDS``` (60 seconds).

Possibly it could also build on the "stubborn robot" code added in 9954f87 for issue #47, but even without that, an improvement from 60 seconds would be good.

**Comment by kotc** [comment]
i think max tradeoffer should be limited to ~10s, 60s seems quite long time, even with humans involved (although clicking 'counter offer' might extend the timeout if human interacts)

**Comment by jdmonin** [comment]
I've added code to look for human players before using the 60-second timeout; that should improve the situation. Thanks again for the idea!

**Comment by jdmonin** [comment]
For practice games, code is part of the latest beta JAR available at http://nand.net/jsettlers/beta2/JSettlers2.jar

**Comment by kotc** [comment]
well, what i meant 'look for human players' is that sometimes bots offer trade only to other bots, even if there are humans in the game too. but even then, i think bots trade offers shouldnt last more than 5-8s for the sake of long pauses in game flow

**Comment by jdmonin** [comment]
OK thanks, that makes sense. Shortened to about 6 seconds when trade is offered only to bots.

**Comment by kotc** [comment]
dont know if it's related, but i'm seeing lots of:
robot 6: debugRandomPauseActive for 12 seconds
etc. with 20190319

**Comment by jdmonin** [comment]
Oh bummer. OK, that's now fixed and re-uploaded.

**Comment by jdmonin** [comment]
Newly released v2.0.00 includes this. Thank you :)
