### ISSUE TITLE
[bug] desert/ore map mismatch

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#60]
build 20190220
i will try attaching screen shot if i can, but generally desert has '8' and ore field has none

https://i.imgur.com/OyTFcb2.png

**Comment by kotc** [comment]
during play i've noticed that 8 didnt result in getting any ore, i forgot to take notice what was happening when i had settlement on 8 and 8 was rolled. also, if you want i have game log archived (~1MB file) i could send you via email etc

**Comment by jdmonin** [comment]
Thanks for the report. That screenshot helps a lot, so I probably won't need the log. I have an idea where this is happening, will take a look at it this week.

**Comment by jdmonin** [comment]
Thanks again for finding this! Bug is fixed, and I added extra testing so it shouldn't come up again.

I also saw in your screenshot that buttons were getting the wrong background color. I think that's fixed, they should be more visible now.
