### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by colinwerner** [jdmonin/JSettlers2#63]
As of 4fbf79548442f72d4059947b79ba71735e933014 I can no longer build. I did not spend much time debugging it yet.

JSettlers2 $ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/colinwerner/github/JSettlers2/build.gradle' line: 117

* What went wrong:
A problem occurred evaluating root project 'JSettlers2'.
> Could not get unknown property 'classesDir' for extra test classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

**Comment by jdmonin** [comment]
I'm taking a look, sorry for the inconvenience. You probably have a newer gradle than I do and it's more strict; what version are you using?  Meanwhile please feel free to copy build.gradle from an earlier commit; it should work for everything except extraTest.

**Comment by jdmonin** [comment]
ok, I can repro the problem in gradle 5.2.1, and 4.10.3 gives:  
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.`

Working on it :)

**Comment by jdmonin** [comment]
OK, I've made and tested master commit 5303880 which hopefully should fix this for you, so please let me know how it goes.

Sorry again to have broken your build and missed it!  I'll test future build.gradle changes in both gradle 4 and gradle 5.

**Comment by colinwerner** [comment]
Sorry for the lack of response on my part! And no worries about the compilation error, I was able to comment out the offending section to continue my work!

**Comment by jdmonin** [comment]
OK thanks, glad to hear!
