### ISSUE TITLE
Suggestion: Timer

### ISSUE THREAD

**Issue by dannythunder** [jdmonin/JSettlers2#68]
Implement a timer in settings so a turn dont go on "forever".

**Comment by jdmonin** [comment]
Hi, thanks for the suggestion! Would this be for human players or bots? About how long starts to feel too long?

**Comment by dannythunder** [comment]
For both. 

I would say 60-100 seconds as optional settings.

**Comment by jdmonin** [comment]
OK, I looked into robot behavior, and reduced the trade offer max wait time from 100 to 30 seconds (commit f2054ac).

Further reduction will take some more thought. We'll need to especially be careful about ending human player turns without being rude or losing opportunities to take actions.

**Comment by jdmonin** [comment]
Human player time limit added to roadmap/todo list. Thanks again!
