### ISSUE TITLE
Bugs in "Through the desert" and "The forgotten tribe"

### ISSUE THREAD

**Issue by Michi-3** [jdmonin/JSettlers2#71]
In the scenario "Through the desert", it is not possible to build roads on some spaces between desert and ocean tiles. I marked those in the attached  screenshots.

In the scenario "The forgotten tribe", when playing with 5 or 6 players, and using the special building phase, the following has happened: When placing a port during the special building phase (due to building a ship), the turn order gets messed up, and the next turn is done by the player on the left to the player building the ship. Also, the victory points shown in the end are not consistent (for some players, svp are added to the total victory points, for others not).

[JSettlers.zip](https://github.com/jdmonin/JSettlers2/files/4593912/JSettlers.zip)

**Comment by jdmonin** [comment]
Hi,
Thank you for letting us know about these! I should have time this weekend to look into it. The screenshots help a lot, so thanks for taking the time to annotate and attach them.

**Comment by jdmonin** [comment]
I've updated the server to fix the "Through The desert" coastal desert road and "Forgotten Tribe"'s special building port turn order bugs. Thanks again!

The Victory Point display bug looks a little trickier. I'll keep at it.

**Comment by Michi-3** [comment]
Thanks for the update! And thanks for the great work on the project. We had much fun playing with it, it works really nice!

**Comment by jdmonin** [comment]
Thanks, glad you're enjoying it! I have a lot of fun working on this project :)

**Comment by jdmonin** [comment]
OK, that Victory Point bug is fixed; it was more insidious than I thought. If a ship claimed a Special Victory Point and then was moved, the SVP was silently deducted from the player. 

Server has been updated and restarted with the fix. Enjoy, and thanks again for your detailed report :)

**Comment by jdmonin** [comment]
This fix was released as part of v2.3.00. Thanks again!
