### ISSUE TITLE
Add cities and knights variation 

### ISSUE THREAD

**Issue by sudosaket** [jdmonin/JSettlers2#72]

**Comment by jdmonin** [comment]
Hi,

Cities and Knights is one of my favorites too.  It's been on my Todo list to implement for a while, but there would be a lot of details to implement. Hopefully there will be time this year :)

**Comment by sudosaket** [comment]
> Hi,
> 
> Cities and Knights is one of my favorites too. It's been on my Todo list to implement for a while, but there would be a lot of details to implement. Hopefully there will be time this year :)

That's great! Maybe if I get time, I'll take a look and see if I can make a PR.

**Comment by jdmonin** [comment]
Still on the roadmap for future implementation.
