### ISSUE TITLE
Creating a hex Board

### ISSUE THREAD

**Issue by ATWrootbeer** [jdmonin/JSettlers2#80]
Any way you can explain how you were able to represent the hexagon board, edges, and vertices in some kind of data structure?

**Comment by jdmonin** [comment]
The board and piece info is kept in `soc.game.SOCBoardLarge` and its parent class `SOCBoard`. For the coordinate system, see Readme.developer section "Board layouts and coordinates" which has a diagram: https://github.com/jdmonin/JSettlers2/blob/master/doc/Readme.developer.md#board-layouts-and-coordinates   

Here's the specific structures:

- Hexes: 2D array `hexLayoutLg`
- Ports: 1D array `portsLayout` with port types, edge coordinates, and facing directions
- For convenience there's also a few miscellaneous sets like `nodesOnLand`
- Playing pieces on edges and nodes are in lists: `settlements`, `cities`, `roadsAndShips`
- Each player also keeps similar lists of their own pieces

**Comment by jdmonin** [comment]
The javadocs for SOCBoardLarge, SOCBoard, and those fields have more info.

In my answer here I've focused on the sea board; the classic board uses the same ideas but a less-straightforward coordinate system. 

If something's unclear, let me know. Thank you :)

**Comment by ATWrootbeer** [comment]
Thank you so much for responding!  I am trying to build the regular version
of catan in python. I think I'm starting to understand the three lists of
hex, vertices, and edges, but I'm still confused how to store the
coordinates of the edges when they are diagonal vs horizontal.  Thanks for
your help, I did not expect a response so this has been a very pleasant
surprise.

Best,
Austin

**Comment by jdmonin** [comment]
Glad to help :)  That sounds like a fun project.

In my layout, since the hexes are 2 x 2 units, any edge with an odd row number is vertical. Edges with an even row number are diagonal; a diagonal edge's left-end vertex is its edge coordinate.  To see if a diagonal edge is angled "northeast" or "southeast" I check `row % 4` and `column % 2`.

Enjoy,
-Jeremy

**Comment by ATWrootbeer** [comment]
thank you I really appreciate it! IT's starting to come together. Right now
I'm working on checking for the longest road.  Any ideas?

**Comment by jdmonin** [comment]
You're checking for longest route in an undirected graph, so there's some graph theory literature out there.

JSettlers uses dynamic programming to do a depth-first search of the player's connected roads and ships, tracking depth (length) as it goes, for each player. See comments and code at SOCPlayer.calcLongestRoad2:
https://github.com/jdmonin/JSettlers2/blob/master/src/main/java/soc/game/SOCPlayer.java#L4928

Some things to keep in mind:
- When there's a tie among players' route lengths, the player who previously had Longest Route keeps it
- A player's first and second settlements might not be connected to each other
- An adjacent road and ship aren't connected to each other unless their common node has a settlement or city owned by that player

**Comment by jdmonin** [comment]
If you have any other questions, feel free to open a new issue.
Thanks!
