### ISSUE TITLE
initial (new/connect/practice) window doesnt get redrawn after being idled

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#81]
happens after some time when i finish the game, yet i forget to close the main window. the window is functional and is the one from second screenshot

**Comment by kotc** [comment]
https://i.imgur.com/RTWBTkH.png
https://i.imgur.com/4JbACHV.png

**Comment by kotc** [comment]
and it's a 'start a server' window, not the (new/connect/practice), eh

**Comment by jdmonin** [comment]
Thanks, I'll take a look. That window sure does look confused

**Comment by jdmonin** [comment]
If I understand, did you start a server running on your machine, played a game on that server, then left it alone for maybe a couple of hours?

**Comment by kotc** [comment]
exactly, so:
1/ start local server
2/ play game
3/ after finishing the game, close the game window, but dont touch the server/game creation window

after some time (never really measured this, but it's relatively long something times out, so it moves from the screen where you create game to the 'start server' window, but without correctly updating contents. it looks like fields/buttons are there, just java doesnt do a window refresh

**Comment by jdmonin** [comment]
This fix was released as part of v2.5.00. Thanks again!
