### ISSUE TITLE
Show bank resources

### ISSUE THREAD

**Issue by balping** [jdmonin/JSettlers2#85]
In the board game it is sometimes useful to see how many resources the bank has, for example to see which resource might be worth claiming while playing the monopoly card. Also, bank resources can run out.

In JSettlers2, I haven't seen any options to display bank resources except for the number of development cards.

**Comment by jdmonin** [comment]
Hi,

Thank you for the suggestion!

This is on our roadmap/todo list in https://github.com/jdmonin/JSettlers2/blob/master/doc/Readme.developer.md as "Track a limited supply of resource cards". It would definitely be useful when playing a monopoly card. The current code and clients treat the bank resources as unlimited, so there'd be some planning needed to keep things backwards-compatible.

**Comment by balping** [comment]
Sorry, I haven't noticed. Good to know it's on your todo!

**Comment by jdmonin** [comment]
No worries, it's always nice to know what folks are interested in seeing :)
