### ISSUE TITLE
where did those 2vp on red came from?

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#86]
as in title, red bot got 2 additional vp. could it be it scored desert twice?

screenshot:
![QnpHeDh](https://user-images.githubusercontent.com/10637309/111024306-05e3fe80-83d6-11eb-885e-9915a87db135.png)

log:
[g-catan.log](https://github.com/jdmonin/JSettlers2/files/6134391/g-catan.log)

**Comment by jdmonin** [comment]
Hi! Good catch. Looks like it gave red 2 SVP for building on the far side of the desert, but also incorrectly gave 2 more for that coastal build in the middle of the desert.

**Comment by jdmonin** [comment]
Thanks again! Fixed, tested, added unit test too.

This will be part of the next released version. Code is server-side, and will work with any client version which supports the Through the Desert scenario.

**Comment by jdmonin** [comment]
This fix was released as part of v2.5.00. Thanks again!
