### ISSUE TITLE
bot fails to play soldier card, but still gets it counted

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#91]
recently i was playing on clothes map, bot was repeatedly trying to play soldier card, but failed, 'card was returned', but his soldier count would increase. see screenshot. do you need log too?

![catan-19solds](https://user-images.githubusercontent.com/10637309/114019382-da7df380-985d-11eb-918b-abdcc7829d18.png)

**Comment by kotc** [comment]
log is filled with:


  current turn: 6507 messages received:
        SOCRejectOffer:game=game-1200|playerNumber=-1|reasonCode=2
        SOCDiceResult:game=game-1200|param=7
        SOCGameState:game=game-1200|state=50
        SOCDiscardRequest:game=game-1200|numDiscards=4
        SOCDiscardRequest:game=game-1200|numDiscards=4
        SOCDiscardRequest:game=game-1200|numDiscards=4
[last line repeated thousands of times]

**Comment by kotc** [comment]
additionally some parts of the window aren't redrawn after maximize/unmaximize as seen in the screenshot

**Comment by jdmonin** [comment]
Thanks, I'll try to take a look this weekend.

You don't need to make an issue for the redraw bug, that's known about already. Thanks for offering, though :)

**Comment by jdmonin** [comment]
Thanks again for reporting this one! Was a server-side fix; tested against new client, v2.0.00, v1.1.18.

**Comment by jdmonin** [comment]
This fix was released as part of v2.5.00. Thanks again!
