### ISSUE TITLE
enable font antialias in linux

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#92]
as you can see on my screenshots fonts look ugly without it. they are a bit fuzzy with AA, but in my opinion it's better than without

[diff-0004-enable-aa-in-linux.txt](https://github.com/jdmonin/JSettlers2/files/6279353/diff-0004-enable-aa-in-linux.txt)

**Comment by jdmonin** [comment]
This is a nice simple improvement, thank you!

Does it work for you as `("awt.useSystemAAFontSettings","on")` instead of `"lcd_hrgb"` ?  I'd prefer to keep it slightly general.

If I can ask, what linux distro and version are you using?

**Comment by kotc** [comment]
on means no subpixel rendering in theory, lcd_hrgb makes it easier to read what exact subrendering is enabled

**Comment by kotc** [comment]
as for distro, its slackware current, but i think its more about what window manager is running. in my case its fluxbox. i suspect gnome/kde etc might set some env that java is picking up automatically

**Comment by jdmonin** [comment]
ok thanks. What about plain `"lcd"` ?

**Comment by kotc** [comment]
plain lcd is probably same as lcd_hrgb

**Comment by kotc** [comment]
one possible upgrade to the patch is checking if that variable is empty (to honor command line params)

**Comment by jdmonin** [comment]
Good ideas; thanks again. When you have time, please test and let me know if that commit c642e7a works for you.

**Comment by kotc** [comment]
yes, it works (and seems to honor command line -D... too

**Comment by jdmonin** [comment]
Great! Thank you again

**Comment by jdmonin** [comment]
This fix was released as part of v2.5.00. Thanks again!
