### ISSUE TITLE
Bug - Dividing the longest road

### ISSUE THREAD

**Issue by Zbychlew** [jdmonin/JSettlers2#96]
Hello Team,
I found another error case with the longest road (jsettlers version 2.4.00):
1. Player1 creates a layout as shown in the diagram below (A and B are villages, C is empty)
2. Player2 has a road length of 5
3. Player3 builds a village at point C, points do not count - Player1 has the longest road!
```
  |
 /  \
A   B
|    |
\   /
  C
```

**Comment by Zbychlew** [comment]
Sorry my bug, Player1 has a path length of 6.

**Comment by jdmonin** [comment]
No worries; thanks for taking the time to write up the potential bug.
